-- CreateTable
CREATE TABLE `Loker` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nama` VARCHAR(191) NOT NULL,
    `deskripsi` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Lamaran` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `alumnisId` INTEGER NOT NULL,
    `lokerId` INTEGER NOT NULL,
    `berkas` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Lamaran` ADD CONSTRAINT `Lamaran_alumnisId_fkey` FOREIGN KEY (`alumnisId`) REFERENCES `Alumnis`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Lamaran` ADD CONSTRAINT `Lamaran_lokerId_fkey` FOREIGN KEY (`lokerId`) REFERENCES `Loker`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
